### ISSUE TITLE
Option to provide SSL Client Key, SSL Client Certificate for Postgres datasource.

### ISSUE THREAD

**Issue by vishal-kadam** [openshift/grafana#48]
I was trying out a local Grafana deployment in which I have a postgres datasource. I also have a local postgres instance running where all my data is stored. I have SSL enabled on my postgres database. I wish to connect to my postgres database with sslmode=verify-full. In postgres datasource, I cannot see any option to configure SSL client certificate file/filepath, SSL client key/key-file-path, SSL root certificate file/filepath. MySQL, Graphite provides this option though. The image provided by Grafana labs "grafana/grafana:latest" has got options to provide SSL configuration details - 
![grafana](https://user-images.githubusercontent.com/33834843/96825112-fd525200-144d-11eb-8c3c-ca5dfa3d7fa3.PNG)
 
But the image "registry.redhat.io/openshift4/ose-grafana:v4.5" does not provide the options to configure SSL related certificates. Here is a snapshot of the UI when I use the image "registry.redhat.io/openshift4/ose-grafana:v4.5".
![grafana](https://user-images.githubusercontent.com/33834843/96825341-7e114e00-144e-11eb-902f-c58a92d723b2.PNG)

Is there any other way by which I can achieve SSL connection with the database having sslmode=verify-full? Or is this feature already implemented in some other image?

**Comment by simonpasquier** [comment]
The `registry.redhat.io/openshift4/ose-grafana` image is only intended to be used in the context of OpenShift cluster monitoring: its configuration is fully managed by the cluster monitoring operator and the only supported datasource is Prometheus (or anything that implements the Prometheus query API, e.g. Thanos).
